name: Continuous Integration

on:
  push:
    branches:
      - main
      - Development
  pull_request:
    branches:
      - main
      - Development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest fastapi-cli

      - name: Run tests with pytest
        run: pytest
