name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13"

      - name: Install dependencies
        run: |
          tail -n +3 installed_packages.txt | awk '{print $1"=="$2}' > requirements.txt
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings