name: Continuous Delivery - Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run container smoke test
        run: |
          docker run -d --name test-container -p 8080:80 ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
          echo "Waiting for container to start..."
          sleep 15
          echo "Pinging health check endpoint..."
          curl -f http://localhost:8080/health

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Official release for version ${{ github.ref_name }}.
            The Docker image is available at `ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}`.
            See CHANGELOG.md for details.
          draft: false
          prerelease: false
